site_name: rustic_ai
site_url: https://pierian-xyz.github.io/rusticai
repo_url: https://github.com/pierian-xyz/rusticai
repo_name: pierian-xyz/rusticai
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - Message Bus API: design/core/messagebus/api.md
  - Message Bus Architecture: design/core/messagebus/architecture.md
  - Message Bus Guidelines: design/core/messagebus/guidelines.md
  - Message Bus Requirements: design/core/messagebus/requirements.md
  - Message Bus Solution: design/core/messagebus/solution.md
  - Message Bus Usage: design/core/messagebus/usage.md

theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
watch:
  - rustic_ai
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/waynerv/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/pierian-xyz/rusticai
      name: Github
    - icon: material/email
      link: "mailto:inbox@rohitrai.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
